### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by KanaHayama** [TeamFleet/WhoCallsTheFleet-DataManager#2]
构建过程不会停止
![screen shot](https://user-images.githubusercontent.com/15655296/74577778-d601c780-4f45-11ea-9be0-a5f8bb941b7d.png)

我不懂前端开发，试着摸索运行了一下，卡在了上图的位置。
看起来是`app`这个Task没有停止。
nodejs是12.16.0，npm是6.13.4。

请问是我少做了什么吗？
如果成功编译，之后直接在浏览器里运行main.html即可还是说要运行服务器？

**Comment by Diablohu** [comment]
这确实是目前的行为，在升级了 gulp 后，老的 watch 进程有问题，就造成了这个结果

该项目的实际运行方式：

1. 在全局安装 `nw`，个人建议命令：`npm install -g nw --nwjs_build_type=sdk`
2. 在项目目录中运行 `nw`

**Comment by KanaHayama** [comment]
已成功运行，谢谢
